/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agent from "./agent";
export type { agent };
import type * as policy from "./policy";
export type { policy };
import type * as scope from "./scope";
export type { scope };
export type { ACLManager } from "./ACLManager";
export type { ACLManagerProxy } from "./ACLManagerProxy";
export type { ACLProxy } from "./ACLProxy";
export type { ACLStorage } from "./ACLStorage";
export type { AccessControl } from "./AccessControl";
export type { IACLCommons } from "./IACLCommons";
export type { IACLManager } from "./IACLManager";
export type { IAccessControl } from "./IAccessControl";
