/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1822Sol from "./IERC1822.sol";
export type { ierc1822Sol };
export type { BaseProxy } from "./BaseProxy";
export type { BaseUUPSProxy } from "./BaseUUPSProxy";
export type { BaseUUPSStorage } from "./BaseUUPSStorage";
export type { IBaseProxy } from "./IBaseProxy";
export type { IProxy } from "./IProxy";
export type { Proxy } from "./Proxy";
