"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LRoleManagement__factory =
  exports.LRealmManagement__factory =
  exports.LGroupManagement__factory =
  exports.LContextManagement__factory =
  exports.LAccessControl__factory =
    void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LAccessControl__factory_1 = require("./LAccessControl__factory");
Object.defineProperty(exports, "LAccessControl__factory", { enumerable: true, get: function () { return LAccessControl__factory_1.LAccessControl__factory; } });
var LContextManagement__factory_1 = require("./LContextManagement__factory");
Object.defineProperty(exports, "LContextManagement__factory", { enumerable: true, get: function () { return LContextManagement__factory_1.LContextManagement__factory; } });
var LGroupManagement__factory_1 = require("./LGroupManagement__factory");
Object.defineProperty(exports, "LGroupManagement__factory", { enumerable: true, get: function () { return LGroupManagement__factory_1.LGroupManagement__factory; } });
var LRealmManagement__factory_1 = require("./LRealmManagement__factory");
Object.defineProperty(exports, "LRealmManagement__factory", { enumerable: true, get: function () { return LRealmManagement__factory_1.LRealmManagement__factory; } });
var LRoleManagement__factory_1 = require("./LRoleManagement__factory");
Object.defineProperty(exports, "LRoleManagement__factory", { enumerable: true, get: function () { return LRoleManagement__factory_1.LRoleManagement__factory; } });
//# sourceMappingURL=index.js.map